spring:
  application:
    name: api-gateway

  threads:
    virtual:
      enabled: true

  cloud:
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: false
      loadbalancer:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,metrics,prometheus
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when-authorized
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/traces
          timeout: 30s
    logging:
      export:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/logs
          timeout: 30s
  otlp:
    metrics:
      export:
        url: ${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/metrics
        connect-timeout: 5s
        read-timeout: 30s
