spring:
  data:
    redis:
      database: 1

  jpa:
    properties:
      hibernate:
        format_sql: false

  kafka:
    consumer:
      group-id: journal-service

  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 30000

kafka:
  homework-execution-topic: homework-execution
  homework-execution-result: homework-result

s3:
  bucket: homeworks-solutions

journal:
  api:
    base-url: "https://msapi.top-academy.ru/api/v2"

management:
  tracing:
    sampling:
      probability: 0.1