spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  port: 8080
  shutdown: graceful

kafka:
  homework-execution-topic: homework-execution-dev
  homework-result-topic: homework-result-dev
  homework-execution-dlq-topic: homework-execution-dev.DLQ

s3:
  bucket: homeworks-solutions-dev

ai:
  default-provider: GEMINI
  fallback-providers:
    - MISTRAL
  mistral:
    http:
      proxy-host: "vpn.internal"
      proxy-port: 7890
  gemini:
    http:
      proxy-host: "vpn.internal"
      proxy-port: 7890

it-top-ai:
  base-url: http://api-gateway-dev.dev.svc.cluster.local:8080

homework:
  download:
    allowed-hosts: localhost,127.0.0.1,*.top-academy.ru,s3.actimate.ru

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    env:
      show-values: always
    configprops:
      show-values: always