spring:
  autoconfigure:
    exclude:
      - org.telegram.telegrambots.longpolling.starter.TelegramBotStarterConfiguration

backend:
  base-url: http://api-gateway-prod.prod.svc.cluster.local:8080

management:
  tracing:
    sampling:
      probability: 0.1
