spring:
  application:
    name: telegram-bot

  threads:
    virtual:
      enabled: true

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    username: ${TELEGRAM_BOT_USERNAME}
    webhook:
      host: ${TELEGRAM_WEBHOOK_HOST}
      path: webhook
      secret-token: ${TELEGRAM_WEBHOOK_SECRET_TOKEN}

proxy:
  host: ${PROXY_HOST:}
  port: ${PROXY_PORT:0}

server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful

admin:
  telegram-ids: ${ADMIN_TELEGRAM_IDS:}
  services:
    - name: telegram-bot
      actuator-url: http://localhost:${SERVER_PORT:8080}
    - name: journal-service
      actuator-url: ${BACKEND_BASE_URL}

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,refresh
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/traces
    logging:
      export:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/logs
  otlp:
    metrics:
      export:
        url: ${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/metrics
