management:
  observations:
    enable:
      spring:
        security:
          filterchains: false

logging:
  level:
    io.micrometer.registry.otlp.OtlpMeterRegistry: OFF
    io.opentelemetry.exporter.internal.http.HttpExporter: OFF
