spring:
  jpa:
    properties:
      hibernate:
        format_sql: false

  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 3
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 30000

  lifecycle:
    timeout-per-shutdown-phase: 60s

  kafka:
    consumer:
      group-id: ai-executor-prod

server:
  port: 8080
  shutdown: graceful

homework:
  download:
    allowed-hosts: localhost,127.0.0.1,*.top-academy.ru,s3.actimate.ru

s3:
  bucket: homeworks-solutions-prod

kafka:
  homework-execution-topic: homework-execution
  homework-result-topic: homework-result
  homework-execution-dlq-topic: homework-execution.DLQ

management:
  tracing:
    sampling:
      probability: 0.1

ai:
  default-provider: GEMINI
  fallback-providers:
    - MISTRAL
  mistral:
    http:
      proxy-host: "192.168.0.148"
      proxy-port: 7890
  gemini:
    http:
      proxy-host: "192.168.0.148"
      proxy-port: 7890

it-top-ai:
  base-url: http://api-gateway-prod.prod.svc.cluster.local:8080
